/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OpsRouteImport } from './routes/ops'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as PlayBaucuaRouteImport } from './routes/play.baucua'
import { Route as PlayTaixiuRouteImport } from './routes/play.taixiu'
import { Route as PlayXocdiaRouteImport } from './routes/play.xocdia'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OpsRoute = OpsRouteImport.update({
  id: '/ops',
  path: '/ops',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayBaucuaRoute = PlayBaucuaRouteImport.update({
  id: '/play/baucua',
  path: '/play/baucua',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayTaixiuRoute = PlayTaixiuRouteImport.update({
  id: '/play/taixiu',
  path: '/play/taixiu',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayXocdiaRoute = PlayXocdiaRouteImport.update({
  id: '/play/xocdia',
  path: '/play/xocdia',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/ops': typeof OpsRoute
  '/wallet': typeof WalletRoute
  '/api/health': typeof ApiHealthRoute
  '/play/baucua': typeof PlayBaucuaRoute
  '/play/taixiu': typeof PlayTaixiuRoute
  '/play/xocdia': typeof PlayXocdiaRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/ops': typeof OpsRoute
  '/wallet': typeof WalletRoute
  '/api/health': typeof ApiHealthRoute
  '/play/baucua': typeof PlayBaucuaRoute
  '/play/taixiu': typeof PlayTaixiuRoute
  '/play/xocdia': typeof PlayXocdiaRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/ops': typeof OpsRoute
  '/wallet': typeof WalletRoute
  '/api/health': typeof ApiHealthRoute
  '/play/baucua': typeof PlayBaucuaRoute
  '/play/taixiu': typeof PlayTaixiuRoute
  '/play/xocdia': typeof PlayXocdiaRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/ops'
    | '/wallet'
    | '/api/health'
    | '/play/baucua'
    | '/play/taixiu'
    | '/play/xocdia'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/ops'
    | '/wallet'
    | '/api/health'
    | '/play/baucua'
    | '/play/taixiu'
    | '/play/xocdia'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/ops'
    | '/wallet'
    | '/api/health'
    | '/play/baucua'
    | '/play/taixiu'
    | '/play/xocdia'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  OpsRoute: typeof OpsRoute
  WalletRoute: typeof WalletRoute
  ApiHealthRoute: typeof ApiHealthRoute
  PlayBaucuaRoute: typeof PlayBaucuaRoute
  PlayTaixiuRoute: typeof PlayTaixiuRoute
  PlayXocdiaRoute: typeof PlayXocdiaRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ops': {
      id: '/ops'
      path: '/ops'
      fullPath: '/ops'
      preLoaderRoute: typeof OpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/baucua': {
      id: '/play/baucua'
      path: '/play/baucua'
      fullPath: '/play/baucua'
      preLoaderRoute: typeof PlayBaucuaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/taixiu': {
      id: '/play/taixiu'
      path: '/play/taixiu'
      fullPath: '/play/taixiu'
      preLoaderRoute: typeof PlayTaixiuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/xocdia': {
      id: '/play/xocdia'
      path: '/play/xocdia'
      fullPath: '/play/xocdia'
      preLoaderRoute: typeof PlayXocdiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  OpsRoute: OpsRoute,
  WalletRoute: WalletRoute,
  ApiHealthRoute: ApiHealthRoute,
  PlayBaucuaRoute: PlayBaucuaRoute,
  PlayTaixiuRoute: PlayTaixiuRoute,
  PlayXocdiaRoute: PlayXocdiaRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
